### ISSUE TITLE
How to convert onnx for V2H

### ISSUE THREAD

**Issue by baishibona** [renesas-rz/rzv_drp-ai_tvm#26]
I am following the tutorial at "how-to/sample_app/docs/hand_landmark_localization/hrnetv2", and got the following error while trying to compile for V2H.

`
/drp-ai_tvm/tvm/python/tvm/target/target.py:326: UserWarning: target_host parameter is going to be deprecated. Please pass in tvm.target.Target(target, host=target_host) instead.
  warnings.warn(
Function name: tvmgen_default_tvmgen_default_mera_drp_main_0
Model size: 38900225
GraphSize: 38900225
Traceback (most recent call last):
  File "compile_pytorch_model.py", line 93, in <module>
    drp.build(mod, \
  File "python/tvm/relay/mera/drp/build.py", line 262, in tvm.relay.mera.drp.build.build
  File "python/tvm/relay/mera/drp/build.py", line 263, in tvm.relay.mera.drp.build.build
  File "/drp-ai_tvm/tvm/python/tvm/relay/build_module.py", line 364, in build
    graph_json, runtime_mod, params = bld_mod.build(
  File "/drp-ai_tvm/tvm/python/tvm/relay/build_module.py", line 161, in build
    self._build(
  File "/drp-ai_tvm/tvm/python/tvm/_ffi/_ctypes/packed_func.py", line 237, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  14: TVMFuncCall
  13: tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  12: tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::IRModule, tvm::runtime::String const&)
  11: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::relay::backend::GraphExecutorCodegenModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#2}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  10: tvm::relay::backend::GraphExecutorCodegen::Codegen(tvm::IRModule, tvm::relay::Function, tvm::runtime::String)
  9: tvm::transform::Pass::operator()(tvm::IRModule) const
  8: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  7: tvm::transform::SequentialNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  6: tvm::transform::Pass::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  5: tvm::transform::ModulePassNode::operator()(tvm::IRModule, tvm::transform::PassContext const&) const
  4: _ZN3tvm7runtime13PackedFuncObj9ExtractorINS0_16PackedFuncSubObjIZNS0_15TypedPackedFuncIFNS_8IRModuleES5_NS_9transform11PassContextEEE17AssignTypedLambdaIZNS_5relay3tec7LowerTEENS0_6StringENS_17CompilationConfigESt8functionIFvNS_8BaseFuncEEEEUlS5_S7_E_EEvT_EUlRKNS0_7TVMArgsEPNS0_11TVMRetValueEE_EEE4CallEPKS1_SL_SP_
  3: tvm::relay::tec::LowerTE(tvm::IRModule const&, tvm::runtime::String const&, std::function<void (tvm::BaseFunc)>, tvm::CompilationConfig)
  2: tvm::relay::tec::TECompilerImpl::LowerExternalFunctions()
  1: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::runtime::ObjectRef const&)>::AssignTypedLambda<tvm::runtime::Module (*)(tvm::runtime::ObjectRef const&)>(tvm::runtime::Module (*)(tvm::runtime::ObjectRef const&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: tvm::relay::contrib::MERADRPCompiler(tvm::runtime::ObjectRef const&)
  File "/root/drp-tvm-share/src/relay/backend/contrib/mera/drp/mera_drp_codegen.cc", line 1715
TVMError: drp translator toolchain failed: 
Error: Unsupported value V2H is set in PRODUCT variable
`

I noticed a lot of the examples are for V2L, not sure if V2H is an option here. Thanks in advance!

**Comment by hiroyuki-sakamoto** [comment]
Thank you for your inquiry.

Regarding the "hand_landmark_localization" sample, it is currently only available for V2L/Mx due to limited human resources. However, we have taken note of your request to make it available for V2H and will consider it for future development.

**Comment by baishibona** [comment]
@hiroyuki-sakamoto Thanks for you kind reply and confirming the sample is for V2L only for now.
Is there any tutorial which I could follow to make a customized demo for applications similar to "hand_landmark_localization"?

**Comment by hiroyuki-sakamoto** [comment]
Numerous useful AI application sample implementations are available at <https://renesas-rz.github.io/rzv_ai_sdk/5.00/applications.html> , where you might find what you are looking for. 
Please note that these samples are intended to be used as-is, and we do not support customization of the models to meet specific requirements.

**Comment by baishibona** [comment]
Thanks @hiroyuki-sakamoto. 

Closing this thread for now.
