### ISSUE TITLE
Tensorflow support

### ISSUE THREAD

**Issue by jo-tham** [renesas-rz/rzv_drp-ai_tvm#5]
Hi,

I'm looking for clarification/time frame on support for tensorflow.

[drp ai tvm product page](https://www.renesas.com/us/en/application/key-technology/artificial-intelligence/ai-accelerator-drp-ai/ai-tool-drp-ai-tvm#overview) indicates tensorflow support around this time - is it under development?

![image](https://user-images.githubusercontent.com/7353689/227754105-a7627a64-dbb5-4198-b503-2a7be64bf6bb.png)

And would this include tensorflow-lite?

Thanks

**Comment by simobepu** [comment]
Hello jo-tham-san,
Thank you for your question.

> is it under development?
Yes, it is under development.
It was originally scheduled to be released at the end of March, but plans have changed and it will be released at the end of April.
I'm sorry to have kept you waiting.

> And would this include tensorflow-lite?
Yes, It includes tensorflow-lite.
If you use tensorflow saved_model format, you need to convert it to tflite format with TFLiteConverter before using it.
We plan to document this procedure in the tutorial.

**Comment by jo-tham** [comment]
Fantastic, thank you for the update.

**Comment by jo-tham** [comment]
Looks like this project supports tflite now, I'll close this.

Thanks!
